### ISSUE TITLE
It's not possible to output ressource URLs as absolute paths in Development

### ISSUE THREAD

**Issue by svenhoerig** [adonisjs/vite-plugin-adonis#17]
### Package version

3.0.0

### Describe the bug

In my project (AdonisJS 6 + Vite) I have the situation that the resource URLs have to be output as absolute URLs. The resources are integrated into the HTML using `@vite(['resources/css/app.css', 'resources/js/app.js'])`. But all my attempts have failed, the CSS and JS files are always, at least in development mode, only integrated as relative and not absolute URLs.

<img width="549" alt="vite-screenshot" src="https://github.com/user-attachments/assets/a51915bd-9e5f-498f-9680-3feae22032f7">

My use case is, that I have an edge Template which I use to generate a PDF file. In the PDF file the URLs have to be absolute URLs, thats why my resource URLs have to be outputted as absolute URLs.

**Comment by thetutlage** [comment]
I think you can use the `assetsUrl` option. https://docs.adonisjs.com/guides/basics/vite#deploying-assets-to-a-cdn
