### ISSUE TITLE
Update vite version to `6.0.0`

### ISSUE THREAD

**Issue by Barabasbalazs** [adonisjs/vite-plugin-adonis#18]
### Package version

3.0.0

### Describe the bug

[Vite 6](https://vite.dev/blog/announcing-vite6) has recently released, and it would be nice for this plugin to support it as well.

I created this issue because I found out that this package using an older version of Vite has already caused problems when trying to use inertia with Vite and some kind of FE frameworks that already use `6.0.0` and it's new features like default values for `resolve.conditions` (https://vite.dev/guide/migration#default-value-for-resolve-conditions). 

Issue stemming from old version of Vite: https://github.com/adonisjs/inertia-starter-kit/issues/5

I can create a PR for this. I think only the versions of `vite` and `@vavite/multibuild` have to be updated.

**Comment by Barabasbalazs** [comment]
I'm guessing the [inertia](https://github.com/adonisjs/inertia/blob/1.x/package.json) `vite` related dependencies also have to be updated in that case.

**Comment by Julien-R44** [comment]
Yeah, I will take care of it soon. I need to make sure that @vavite/multibuild is compatible with Vite version 6, and I'd also like to see if I can improve the SSR process with the new Vite Environment API.

**Comment by Barabasbalazs** [comment]
The latest version of `@vavite/multibuild` seems to support vite 6 already -> https://github.com/cyco130/vavite/pull/131

**Comment by Julien-R44** [comment]
Released with @adonisjs/vite@4.0.0! 
Thanks again
